// <auto-generated />
using System;
using Arkive_API.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Arkive_API.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Arkive_API.Domain.Entities.CategoriaDoencaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CATEGORIA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_CATEGORIA");

                    b.Property<string>("StAtivo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("ST_ATIVO");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Nome" }, "UQ_ARKIVE_CATEGORIA_NOME")
                        .IsUnique();

                    b.ToTable("TB_ARKIVE_CATEGORIA_DOENCA");
                });

            modelBuilder.Entity("Arkive_API.Domain.Entities.DoencaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DOENCA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CID")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("CD_CID_VET");

                    b.Property<string>("Descricao")
                        .HasColumnType("CLOB")
                        .HasColumnName("DS_DOENCA");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CATEGORIA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_DOENCA");

                    b.Property<string>("Sintomas")
                        .HasColumnType("CLOB")
                        .HasColumnName("DS_SINTOMAS");

                    b.Property<string>("StAtivo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("ST_ATIVO");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex(new[] { "Nome" }, "UQ_ARKIVE_DOENCA_NOME")
                        .IsUnique();

                    b.ToTable("TB_ARKIVE_DOENCA");
                });

            modelBuilder.Entity("Arkive_API.Domain.Entities.EspecieEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ESPECIE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NM_ESPECIE");

                    b.Property<string>("StAtivo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("ST_ATIVO");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Especie" }, "UQ_ARKIVE_ESPECIE_NOME")
                        .IsUnique();

                    b.ToTable("TB_ARKIVE_ESPECIE");
                });

            modelBuilder.Entity("Arkive_API.Domain.Entities.External.AnimalExternal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ANIMAL");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("TB_ARKIVE_ANIMAL");
                });

            modelBuilder.Entity("Arkive_API.Domain.Entities.External.ClinicaExternal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CLINICA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("TB_ARKIVE_CLINICA");
                });

            modelBuilder.Entity("Arkive_API.Domain.Entities.External.ConsultaExternal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CONSULTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("TB_ARKIVE_CONSULTA");
                });

            modelBuilder.Entity("Arkive_API.Domain.Entities.External.ResponsavelExternal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_RESPONSAVEL");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("TB_ARKIVE_RESPONSAVEL");
                });

            modelBuilder.Entity("Arkive_API.Domain.Entities.External.VeterinarioExternal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VETERINARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("TB_ARKIVE_VETERINARIO");
                });

            modelBuilder.Entity("Arkive_API.Domain.Entities.FeedbackNPSEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_FEEDBACK_NPS");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasColumnType("CLOB")
                        .HasColumnName("DS_COMENTARIO");

                    b.Property<DateTime>("DataFeedback")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_FEEDBACK");

                    b.Property<int?>("IdAnimal")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ANIMAL");

                    b.Property<int?>("IdClinica")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<int?>("IdConsulta")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CONSULTA");

                    b.Property<int?>("IdResponsavel")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_RESPONSAVEL");

                    b.Property<int?>("IdVeterinario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VETERINARIO");

                    b.Property<int>("Nota")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NR_NOTA");

                    b.HasKey("Id");

                    b.ToTable("TB_ARKIVE_FEEDBACK_NPS");
                });

            modelBuilder.Entity("Arkive_API.Domain.Entities.PredisposicaoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PREDISPOSICAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdDoenca")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DOENCA");

                    b.Property<int>("IdEspecie")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ESPECIE");

                    b.Property<int?>("IdRaca")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_RACA");

                    b.HasKey("Id");

                    b.HasIndex("IdDoenca");

                    b.HasIndex("IdRaca");

                    b.HasIndex(new[] { "IdEspecie", "IdRaca", "IdDoenca" }, "UX_ARKIVE_PREDISPOSICAO")
                        .IsUnique()
                        .HasFilter("\"ID_RACA\" IS NOT NULL");

                    b.ToTable("TB_ARKIVE_PREDISPOSICAO");
                });

            modelBuilder.Entity("Arkive_API.Domain.Entities.RacaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_RACA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdEspecie")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ESPECIE");

                    b.Property<string>("Porte")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TP_PORTE");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NM_RACA");

                    b.Property<string>("StAtivo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("ST_ATIVO");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdEspecie", "Raca" }, "UQ_ARKIVE_RACA_ESPECIE_NOME")
                        .IsUnique();

                    b.ToTable("TB_ARKIVE_RACA");
                });

            modelBuilder.Entity("Arkive_API.Domain.Entities.DoencaEntity", b =>
                {
                    b.HasOne("Arkive_API.Domain.Entities.CategoriaDoencaEntity", "Categoria")
                        .WithMany("Doencas")
                        .HasForeignKey("IdCategoria");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Arkive_API.Domain.Entities.PredisposicaoEntity", b =>
                {
                    b.HasOne("Arkive_API.Domain.Entities.DoencaEntity", "Doenca")
                        .WithMany("Predisposicoes")
                        .HasForeignKey("IdDoenca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arkive_API.Domain.Entities.EspecieEntity", "Especie")
                        .WithMany("Predisposicoes")
                        .HasForeignKey("IdEspecie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arkive_API.Domain.Entities.RacaEntity", "Raca")
                        .WithMany("Predisposicoes")
                        .HasForeignKey("IdRaca");

                    b.Navigation("Doenca");

                    b.Navigation("Especie");

                    b.Navigation("Raca");
                });

            modelBuilder.Entity("Arkive_API.Domain.Entities.RacaEntity", b =>
                {
                    b.HasOne("Arkive_API.Domain.Entities.EspecieEntity", "Especie")
                        .WithMany("Racas")
                        .HasForeignKey("IdEspecie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("Arkive_API.Domain.Entities.CategoriaDoencaEntity", b =>
                {
                    b.Navigation("Doencas");
                });

            modelBuilder.Entity("Arkive_API.Domain.Entities.DoencaEntity", b =>
                {
                    b.Navigation("Predisposicoes");
                });

            modelBuilder.Entity("Arkive_API.Domain.Entities.EspecieEntity", b =>
                {
                    b.Navigation("Predisposicoes");

                    b.Navigation("Racas");
                });

            modelBuilder.Entity("Arkive_API.Domain.Entities.RacaEntity", b =>
                {
                    b.Navigation("Predisposicoes");
                });
#pragma warning restore 612, 618
        }
    }
}
